[package]
edition = "2021"
name = "littlefighter2"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = "0.7.0"
bevy-parallax = "0.1.2"
bevy_rapier2d = { version = "0.14.1", features = ["debug-render"] }
